import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
// const defaultEndpoint = "https://rickandmortyapi.com/api/character/";
const defaultEndpoint = "http://localhost:4000/groups";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  //console.log(data);
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { results } = data;
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Elevation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>
      <main className={styles.main}>
        <h1 className={styles.title}>Elevation Groups</h1>

        <p className={styles.description}>Find a group near you today!</p>
        <ul className={styles.grid}>
          {data.map((result) => {
            const {
              id,
              campus,
              demographic,
              group_type,
              meeting_date,
              zip_code,
            } = result;

            return (
              <li key={id} className={styles.card}>
                <h2>Location: {campus}</h2>
                <div>
                  <p>
                    <strong>Category: </strong>{demographic}
                  </p>
                  <p>
                    <strong>Group:</strong> {group_type}
                  </p>
                  <p>
                    <strong>Date:</strong> {meeting_date}
                  </p>
                  <p>
                    <strong>Zipcode:</strong> {zip_code}
                  </p>
                </div>
              </li>
            );
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <div className={styles.container}>
          <p>11416 E. Independence Blvd, Suite N, Matthews, NC, 28105</p>
          <p>(704) 246-0800</p>
        </div>
      </footer>
    </div>
  );
}
